use_frameworks!

platform :ios, '8.0'

target 'zhenjingxiongTool_Example' do
  pod 'zhenjingxiongTool', :path => '../'

  target 'zhenjingxiongTool_Tests' do
    inherit! :search_paths

    
  end
end
